# Based on output from `helm template` with https://github.com/kubernetes-incubator/external-storage/tree/master/local-volume/helm 
---
# Source: provisioner/templates/provisioner.yaml

apiVersion: v1
kind: ConfigMap
metadata:
  name: local-provisioner-config 
  namespace: default 
data:
  storageClassMap: |
    local-storage:     
      hostDir: /mnt/local-storage
      mountDir:  /mnt/local-storage 

---

apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: local-volume-provisioner
  namespace: default
  labels:
    app: local-volume-provisioner
spec:
  selector:
    matchLabels:
      app: local-volume-provisioner 
  template:
    metadata:
      labels:
        app: local-volume-provisioner
    spec:
      serviceAccountName: local-storage-admin
      containers:
        - image: "quay.io/external_storage/local-volume-provisioner:latest"
          imagePullPolicy: "Always"
          name: provisioner 
          securityContext:
            privileged: true
          env:
          volumeMounts:
            - mountPath: /etc/provisioner/config 
              name: provisioner-config
              readOnly: true
#
# Populating entries with user provided disk discovery directories 
#
            - mountPath:  /mnt/local-storage 
              name: local-storage
      volumes:
        - name: provisioner-config
          configMap:
            name: local-provisioner-config
        - name: local-storage
          hostPath:
            path: /mnt/local-storage

