apiVersion: kubeadm.k8s.io/v1alpha1
kind: MasterConfiguration
token: #token#
tokenTTL: 999999h
api:
  advertiseAddress: 192.168.38.11
networking:
  # Flannel
  podSubnet: 10.244.0.0/16
featureGates:
  SelfHosting: true
  #HighAvailability: true
  #PersistentLocalVolumes: true
  #VolumeScheduling: true
  #MountPropagation: true
apiServerExtraArgs:
  # https://kubernetes.io/docs/reference/generated/kube-apiserver/
  service-node-port-range: 80-32767
  feature-gates: "PersistentLocalVolumes=true,VolumeScheduling=true,MountPropagation=true"
controllerManagerExtraArgs:
  # https://kubernetes.io/docs/reference/generated/kube-controller-manager/
  feature-gates: "PersistentLocalVolumes=true,VolumeScheduling=true,MountPropagation=true"
schedulerExtraArgs:
  # https://kubernetes.io/docs/reference/generated/kube-scheduler/
  feature-gates: "PersistentLocalVolumes=true,VolumeScheduling=true,MountPropagation=true"
