---
apiVersion: v1
kind: Namespace
metadata:
  name: channel
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: cluster-perimeter
  namespace: channel
spec:
  replicas: 1
  selector:
    matchLabels:
      role: channel
  template:
    metadata:
      labels:
        role: channel
    spec:
      containers:
      - name: stub
        image: solsson/http-echo@sha256:a6e24bd4bd1388d50b16c3da1652fbb6effdfdd23a9fe565712c6b73120a3826
        ports:
        - name: http
          containerPort: 80
          hostPort: 80
        - name: https
          containerPort: 443
          hostPort: 443
---
kind: Service
apiVersion: v1
metadata:
  name: perimeter
  namespace: channel
spec:
  type: ClusterIP
  selector:
    role: channel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: perimeter-port80
  namespace: channel
spec:
  type: NodePort
  selector:
    role: channel
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 80
---
kind: Pod
apiVersion: v1
metadata:
  name: test
  namespace: channel
spec:
  containers:
  - name: curl
    image: solsson/curl
    command:
    - tail
    - -f
    - /dev/null
